# Generated by Django 5.1.4 on 2024-12-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Завод", "fabric"),
                            ("Розничная сеть", "retail"),
                            (
                                "Индивидуальный предприниматель",
                                "individual_entrepreneur",
                            ),
                        ],
                        help_text="Укажите тип компании",
                        max_length=150,
                        verbose_name="Тип компании",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название компании",
                        max_length=250,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "Фабрика - 0 уровень"),
                            (1, "Поставщик от фабрики - 1 уровень"),
                            (2, "Поставщик поставщика - 2 уровень"),
                        ],
                        help_text="Укажите номер уровня иерархии",
                        verbose_name="Номер уровня иерархии",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Укажите описание компании",
                        null=True,
                        verbose_name="Описание компании",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        help_text="Укажите поставщика",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="retail_chain.company",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
        ),
    ]
