# Generated by Django 5.1.4 on 2024-12-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Компания", "verbose_name_plural": "Компании"},
        ),
        migrations.AlterField(
            model_name="company",
            name="type",
            field=models.CharField(
                choices=[
                    ("fabric", "Завод"),
                    ("retail", "Розничная сеть"),
                    ("individual_entrepreneur", "Индивидуальный предприниматель"),
                ],
                help_text="Укажите тип компании",
                max_length=150,
                verbose_name="Тип компании",
            ),
        ),
    ]
