# Generated by Django 5.1.4 on 2024-12-21 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_chain", "0002_alter_company_options_alter_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите поставщика",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="retail_chain.company",
                verbose_name="Поставщик",
            ),
        ),
    ]
