# Generated by Django 5.1.4 on 2024-12-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail_chain", "0009_alter_company_products_alter_contacts_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_model",
            field=models.CharField(
                help_text="Укажите модель продукта",
                max_length=150,
                verbose_name="Модель продукта",
            ),
        ),
    ]
